### ISSUE TITLE
プロジェクト構成について

### ISSUE THREAD

**Issue by k1203t** [ezeuok/docker-for-study-laravel#1]
今の構成でソースとdockerのプロジェクトを分けるのもいいと思いますが、
docker使うのが前提であれば、docker-for-study-laravelプロジェクトにソースコードも入れて、
volumeで参照する方が開発しやすいような気がしました。
こんな感じです。
https://github.com/webdevops/php-docker-boilerplate
https://github.com/aveferrum/angular-material-demo

あとアプリのログはどこに出力するのかは気になりました。

**Comment by ezeuok** [comment]
@k1203t 意見ありがとうございます！ 😃 

サーバー環境だけが必要で、違うアプリを試したりする場合もあるかと思ってrepositoryを分けていますが、言われて見ると、だったらdocker-for-study-laravelのrepository名はおかしいですね。
study-laravelの専用に見えますし。
これは宿題とします。

volumeに関しては、一応hostとの共有directoryにアプリソースをcloneして開発するような仕組みになっています。アプリlogはlaravel勉強がまだそこまで進んでないので設定はしていないですが、アプリproject内のどこかに書き出すことを考えています。

あと、リンク先ありがとうございます！

**Comment by ezeuok** [comment]
@k1203t ⬆️ 5d7aaa9 で設置手順を少し改善し、説明を修正しました！
宿題は一旦解決ということでcloseします。
ありがとうございました！ 😃
